INSERT INTO fylker (fylke_navn) VALUES
    ('Østfold'),
    ('Akershus'),
    ('Oslo'),
    ('Hedmark'),
    ('Oppland'),
    ('Buskerud'),
    ('Vestfold'),
    ('Telemark'),
    ('Aust-Agder'),
    ('Vest-Agder'),
    ('Rogaland'),
    ('Hordaland'),
    ('Sogn og Fjordane'),
    ('Møre og Romsdal'),
    ('Trøndelag'),
    ('Nordland'),
    ('Troms'),
    ('Finnmark');


INSERT INTO kommuner (fylke_navn, kommune_navn) VALUES
    ('Østfold', 'Halden'),
    ('Østfold', 'Moss'),
    ('Østfold', 'Sarpsborg'),
    ('Østfold', 'Fredrikstad'),
    ('Østfold', 'Hvaler'),
    ('Østfold', 'Aremark'),
    ('Østfold', 'Marker'),
    ('Østfold', 'Rømskog'),
    ('Østfold', 'Trøgstad'),
    ('Østfold', 'Spydeberg'),
    ('Østfold', 'Askim'),
    ('Østfold', 'Eidsberg'),
    ('Østfold', 'Skiptvet'),
    ('Østfold', 'Rakkestad'),
    ('Østfold', 'Råde'),
    ('Østfold', 'Rygge'),
    ('Østfold', 'Våler'),
    ('Østfold', 'Hobøl'),
    ('Akershus', 'Vestby'),
    ('Akershus', 'Ski'),
    ('Akershus', 'Ås'),
    ('Akershus', 'Frogn'),
    ('Akershus', 'Nesodden'),
    ('Akershus', 'Oppegård'),
    ('Akershus', 'Bærum'),
    ('Akershus', 'Asker'),
    ('Akershus', 'Aurskog-Høland'),
    ('Akershus', 'Sørum'),
    ('Akershus', 'Fet'),
    ('Akershus', 'Rælingen'),
    ('Akershus', 'Enebakk'),
    ('Akershus', 'Lørenskog'),
    ('Akershus', 'Skedsmo'),
    ('Akershus', 'Nittedal'),
    ('Akershus', 'Gjerdrum'),
    ('Akershus', 'Ullensaker'),
    ('Akershus', 'Nes'),
    ('Akershus', 'Eidsvoll'),
    ('Akershus', 'Nannestad'),
    ('Akershus', 'Hurdal'),
    ('Oslo', 'Oslo'),
    ('Hedmark', 'Kongsvinger'),
    ('Hedmark', 'Hamar'),
    ('Hedmark', 'Ringsaker'),
    ('Hedmark', 'Løten'),
    ('Hedmark', 'Stange'),
    ('Hedmark', 'Nord-Odal'),
    ('Hedmark', 'Sør-Odal'),
    ('Hedmark', 'Eidskog'),
    ('Hedmark', 'Grue'),
    ('Hedmark', 'Åsnes'),
    ('Hedmark', 'Våler'),
    ('Hedmark', 'Elverum'),
    ('Hedmark', 'Trysil'),
    ('Hedmark', 'Åmot'),
    ('Hedmark', 'Stor-Elvdal'),
    ('Hedmark', 'Rendalen'),
    ('Hedmark', 'Engerdal'),
    ('Hedmark', 'Tolga'),
    ('Hedmark', 'Tynset'),
    ('Hedmark', 'Alvdal'),
    ('Hedmark', 'Folldal'),
    ('Hedmark', 'Os'),
    ('Oppland', 'Lillehammer'),
    ('Oppland', 'Gjøvik'),
    ('Oppland', 'Dovre'),
    ('Oppland', 'Lesja'),
    ('Oppland', 'Skjåk'),
    ('Oppland', 'Lom'),
    ('Oppland', 'Vågå'),
    ('Oppland', 'Nord-Fron'),
    ('Oppland', 'Sel'),
    ('Oppland', 'Sør-Fron'),
    ('Oppland', 'Ringebu'),
    ('Oppland', 'Øyer'),
    ('Oppland', 'Gausdal'),
    ('Oppland', 'Østre Toten'),
    ('Oppland', 'Vestre Toten'),
    ('Oppland', 'Jevnaker'),
    ('Oppland', 'Lunner'),
    ('Oppland', 'Gran'),
    ('Oppland', 'Søndre Land'),
    ('Oppland', 'Nordre Land'),
    ('Oppland', 'Sør-Aurdal'),
    ('Oppland', 'Etnedal'),
    ('Oppland', 'Nord-Aurdal'),
    ('Oppland', 'Vestre Slidre'),
    ('Oppland', 'Øystre Slidre'),
    ('Oppland', 'Vang'),
    ('Buskerud', 'Drammen'),
    ('Buskerud', 'Kongsberg'),
    ('Buskerud', 'Ringerik'),
    ('Buskerud', 'Hole'),
    ('Buskerud', 'Flå'),
    ('Buskerud', 'Nes'),
    ('Buskerud', 'Gol'),
    ('Buskerud', 'Hemsedal'),
    ('Buskerud', 'Ål'),
    ('Buskerud', 'Hol'),
    ('Buskerud', 'Sigdal'),
    ('Buskerud', 'Krødsherad'),
    ('Buskerud', 'Modum'),
    ('Buskerud', 'Øvre Eiker'),
    ('Buskerud', 'Nedre Eike'),
    ('Buskerud', 'Lier'),
    ('Buskerud', 'Røyken'),
    ('Buskerud', 'Hurum'),
    ('Buskerud', 'Flesberg'),
    ('Buskerud', 'Rollag'),
    ('Buskerud', 'Nore og Uvdal'),
    ('Vestfold', 'Horten'),
    ('Vestfold', 'Tønsberg'),
    ('Vestfold', 'Sandefjord'),
    ('Vestfold', 'Svelvik'),
    ('Vestfold', 'Larvik'),
    ('Vestfold', 'Sande'),
    ('Vestfold', 'Holmestrand'),
    ('Vestfold', 'Re'),
    ('Vestfold', 'Færder'),
    ('Telemark', 'Porsgrunn'),
    ('Telemark', 'Skien'),
    ('Telemark', 'Notodden'),
    ('Telemark', 'Siljan'),
    ('Telemark', 'Bamble'),
    ('Telemark', 'Kragerø'),
    ('Telemark', 'Drangedal'),
    ('Telemark', 'Nome'),
    ('Telemark', 'Bø'),
    ('Telemark', 'Sauherad'),
    ('Telemark', 'Tinn'),
    ('Telemark', 'Hjartdal'),
    ('Telemark', 'Seljord'),
    ('Telemark', 'Kviteseid'),
    ('Telemark', 'Nissedal'),
    ('Telemark', 'Fyresdal'),
    ('Telemark', 'Tokke'),
    ('Telemark', 'Vinje'),
    ('Aust-Agder', 'Risør'),
    ('Aust-Agder', 'Grimstad'),
    ('Aust-Agder', 'Arendal'),
    ('Aust-Agder', 'Gjerstad'),
    ('Aust-Agder', 'Vegårshei'),
    ('Aust-Agder', 'Tvedestrand'),
    ('Aust-Agder', 'Froland'),
    ('Aust-Agder', 'Lillesand'),
    ('Aust-Agder', 'Birkenes'),
    ('Aust-Agder', 'Åmli'),
    ('Aust-Agder', 'Iveland'),
    ('Aust-Agder', 'Evje og Hornnes'),
    ('Aust-Agder', 'Bygland'),
    ('Aust-Agder', 'Valle'),
    ('Aust-Agder', 'Bykle'),
    ('Vest-Agder', 'Kristiansand'),
    ('Vest-Agder', 'Mandal'),
    ('Vest-Agder', 'Farsund'),
    ('Vest-Agder', 'Flekkefjord'),
    ('Vest-Agder', 'Vennesla'),
    ('Vest-Agder', 'Songdalen'),
    ('Vest-Agder', 'Søgne'),
    ('Vest-Agder', 'Marnardal'),
    ('Vest-Agder', 'Åseral'),
    ('Vest-Agder', 'Audnedal'),
    ('Vest-Agder', 'Lindesnes'),
    ('Vest-Agder', 'Lyngdal'),
    ('Vest-Agder', 'Hægebostad'),
    ('Vest-Agder', 'Kvinesdal'),
    ('Vest-Agder', 'Sirdal'),
    ('Rogaland', 'Eigersund'),
    ('Rogaland', 'Sandnes'),
    ('Rogaland', 'Stavanger'),
    ('Rogaland', 'Haugesund'),
    ('Rogaland', 'Sokndal'),
    ('Rogaland', 'Lund'),
    ('Rogaland', 'Bjerkreim'),
    ('Rogaland', 'Hå'),
    ('Rogaland', 'Klepp'),
    ('Rogaland', 'Time'),
    ('Rogaland', 'Gjesdal'),
    ('Rogaland', 'Sola'),
    ('Rogaland', 'Randaberg'),
    ('Rogaland', 'Forsand'),
    ('Rogaland', 'Strand'),
    ('Rogaland', 'Hjelmeland'),
    ('Rogaland', 'Suldal'),
    ('Rogaland', 'Sauda'),
    ('Rogaland', 'Finnøy'),
    ('Rogaland', 'Rennesøy'),
    ('Rogaland', 'Kvitsøy'),
    ('Rogaland', 'Bokn'),
    ('Rogaland', 'Tysvær'),
    ('Rogaland', 'Karmøy'),
    ('Rogaland', 'Utsira'),
    ('Rogaland', 'Vindafjord'),
    ('Hordaland', 'Bergen'),
    ('Hordaland', 'Etne'),
    ('Hordaland', 'Sveio'),
    ('Hordaland', 'Bømlo'),
    ('Hordaland', 'Stord'),
    ('Hordaland', 'Fitjar'),
    ('Hordaland', 'Tysnes'),
    ('Hordaland', 'Kvinnherad'),
    ('Hordaland', 'Jondal'),
    ('Hordaland', 'Odda'),
    ('Hordaland', 'Ullensvang'),
    ('Hordaland', 'Eidfjord'),
    ('Hordaland', 'Ulvik'),
    ('Hordaland', 'Granvin'),
    ('Hordaland', 'Voss'),
    ('Hordaland', 'Kvam'),
    ('Hordaland', 'Fusa'),
    ('Hordaland', 'Samnanger'),
    ('Hordaland', 'Os'),
    ('Hordaland', 'Austevoll'),
    ('Hordaland', 'Sund'),
    ('Hordaland', 'Fjell'),
    ('Hordaland', 'Askøy'),
    ('Hordaland', 'Vaksdal'),
    ('Hordaland', 'Modalen'),
    ('Hordaland', 'Osterøy'),
    ('Hordaland', 'Meland'),
    ('Hordaland', 'Øygarden'),
    ('Hordaland', 'Radøy'),
    ('Hordaland', 'Lindås'),
    ('Hordaland', 'Austrheim'),
    ('Hordaland', 'Fedje'),
    ('Hordaland', 'Masfjorden'),
    ('Sogn og Fjordane', 'Flora'),
    ('Sogn og Fjordane', 'Gulen'),
    ('Sogn og Fjordane', 'Solund'),
    ('Sogn og Fjordane', 'Hyllestad'),
    ('Sogn og Fjordane', 'Høyanger'),
    ('Sogn og Fjordane', 'Vik'),
    ('Sogn og Fjordane', 'Balestrand'),
    ('Sogn og Fjordane', 'Leikanger'),
    ('Sogn og Fjordane', 'Sogndal'),
    ('Sogn og Fjordane', 'Aurland'),
    ('Sogn og Fjordane', 'Lærdal'),
    ('Sogn og Fjordane', 'Årdal'),
    ('Sogn og Fjordane', 'Luster'),
    ('Sogn og Fjordane', 'Askvoll'),
    ('Sogn og Fjordane', 'Fjaler'),
    ('Sogn og Fjordane', 'Gaular'),
    ('Sogn og Fjordane', 'Jølster'),
    ('Sogn og Fjordane', 'Førde'),
    ('Sogn og Fjordane', 'Naustdal'),
    ('Sogn og Fjordane', 'Bremanger'),
    ('Sogn og Fjordane', 'Vågsøy'),
    ('Sogn og Fjordane', 'Selje'),
    ('Sogn og Fjordane', 'Eid'),
    ('Sogn og Fjordane', 'Hornindal'),
    ('Sogn og Fjordane', 'Gloppen'),
    ('Sogn og Fjordane', 'Stryn'),
    ('Møre og Romsdal', 'Molde'),
    ('Møre og Romsdal', 'Ålesund'),
    ('Møre og Romsdal', 'Kristiansund'),
    ('Møre og Romsdal', 'Vanylven'),
    ('Møre og Romsdal', 'Sande'),
    ('Møre og Romsdal', 'Herøy'),
    ('Møre og Romsdal', 'Ulstein'),
    ('Møre og Romsdal', 'Hareid'),
    ('Møre og Romsdal', 'Volda'),
    ('Møre og Romsdal', 'Ørsta'),
    ('Møre og Romsdal', 'Ørskog'),
    ('Møre og Romsdal', 'Norddal'),
    ('Møre og Romsdal', 'Stranda'),
    ('Møre og Romsdal', 'Stordal'),
    ('Møre og Romsdal', 'Sykkylven'),
    ('Møre og Romsdal', 'Skodje'),
    ('Møre og Romsdal', 'Sula'),
    ('Møre og Romsdal', 'Giske'),
    ('Møre og Romsdal', 'Haram'),
    ('Møre og Romsdal', 'Vestnes'),
    ('Møre og Romsdal', 'Rauma'),
    ('Møre og Romsdal', 'Nesset'),
    ('Møre og Romsdal', 'Midsund'),
    ('Møre og Romsdal', 'Sandøy'),
    ('Møre og Romsdal', 'Aukra'),
    ('Møre og Romsdal', 'Fræna'),
    ('Møre og Romsdal', 'Eide'),
    ('Møre og Romsdal', 'Averøy'),
    ('Møre og Romsdal', 'Gjemnes'),
    ('Møre og Romsdal', 'Tingvoll'),
    ('Møre og Romsdal', 'Sunndal'),
    ('Møre og Romsdal', 'Surnadal'),
    ('Møre og Romsdal', 'Rindal'),
    ('Møre og Romsdal', 'Halsa'),
    ('Møre og Romsdal', 'Smøla'),
    ('Møre og Romsdal', 'Aure'),
    ('Trøndelag', 'Trondheim'),
    ('Trøndelag', 'Steinkjer'),
    ('Trøndelag', 'Namsos'),
    ('Trøndelag', 'Hemne'),
    ('Trøndelag', 'Snillfjord'),
    ('Trøndelag', 'Hitra'),
    ('Trøndelag', 'Frøya'),
    ('Trøndelag', 'Ørland'),
    ('Trøndelag', 'Agdenes'),
    ('Trøndelag', 'Bjugn'),
    ('Trøndelag', 'Åfjord'),
    ('Trøndelag', 'Roan'),
    ('Trøndelag', 'Osen'),
    ('Trøndelag', 'Oppdal'),
    ('Trøndelag', 'Rennebu'),
    ('Trøndelag', 'Meldal'),
    ('Trøndelag', 'Orkdal'),
    ('Trøndelag', 'Røros'),
    ('Trøndelag', 'Holtålen'),
    ('Trøndelag', 'Midtre Gauldal'),
    ('Trøndelag', 'Melhus'),
    ('Trøndelag', 'Skaun'),
    ('Trøndelag', 'Klæbu'),
    ('Trøndelag', 'Malvik'),
    ('Trøndelag', 'Selbu'),
    ('Trøndelag', 'Tydal'),
    ('Trøndelag', 'Meråker'),
    ('Trøndelag', 'Stjørdal'),
    ('Trøndelag', 'Frosta'),
    ('Trøndelag', 'Levanger'),
    ('Trøndelag', 'Verdal'),
    ('Trøndelag', 'Verran'),
    ('Trøndelag', 'Namdalseid'),
    ('Trøndelag', 'Snåsa'),
    ('Trøndelag', 'Lierne'),
    ('Trøndelag', 'Røyrvik'),
    ('Trøndelag', 'Namsskogan'),
    ('Trøndelag', 'Grong'),
    ('Trøndelag', 'Høylandet'),
    ('Trøndelag', 'Overhalla'),
    ('Trøndelag', 'Fosnes'),
    ('Trøndelag', 'Flatanger'),
    ('Trøndelag', 'Vikna'),
    ('Trøndelag', 'Nærøy'),
    ('Trøndelag', 'Leka'),
    ('Trøndelag', 'Inderøy'),
    ('Trøndelag', 'Indre Fosen'),
    ('Nordland', 'Bodø'),
    ('Nordland', 'Narvik'),
    ('Nordland', 'Bindal'),
    ('Nordland', 'Sømna'),
    ('Nordland', 'Brønnøy'),
    ('Nordland', 'Vega'),
    ('Nordland', 'Vevelstad'),
    ('Nordland', 'Herøy'),
    ('Nordland', 'Alstahaug'),
    ('Nordland', 'Leirfjord'),
    ('Nordland', 'Vefsn'),
    ('Nordland', 'Grane'),
    ('Nordland', 'Hattfjelldal'),
    ('Nordland', 'Dønna'),
    ('Nordland', 'Nesna'),
    ('Nordland', 'Hemnes'),
    ('Nordland', 'Rana'),
    ('Nordland', 'Lurøy'),
    ('Nordland', 'Træna'),
    ('Nordland', 'Rødøy'),
    ('Nordland', 'Meløy'),
    ('Nordland', 'Gildeskål'),
    ('Nordland', 'Beiarn'),
    ('Nordland', 'Saltdal'),
    ('Nordland', 'Fauske'),
    ('Nordland', 'Sørfold'),
    ('Nordland', 'Steigen'),
    ('Nordland', 'Hamarøy'),
    ('Nordland', 'Tysfjord'),
    ('Nordland', 'Lødingen'),
    ('Nordland', 'Tjeldsund'),
    ('Nordland', 'Evenes'),
    ('Nordland', 'Ballangen'),
    ('Nordland', 'Røst'),
    ('Nordland', 'Værøy'),
    ('Nordland', 'Flakstad'),
    ('Nordland', 'Vestvågøy'),
    ('Nordland', 'Vågan'),
    ('Nordland', 'Hadsel'),
    ('Nordland', 'Bø'),
    ('Nordland', 'Øksnes'),
    ('Nordland', 'Sortland'),
    ('Nordland', 'Andøy'),
    ('Nordland', 'Moskenes'),
    ('Troms', 'Harstad'),
    ('Troms', 'Tromsø'),
    ('Troms', 'Kvæfjord'),
    ('Troms', 'Skånland'),
    ('Troms', 'Ibestad'),
    ('Troms', 'Gratangen'),
    ('Troms', 'Lavangen'),
    ('Troms', 'Bardu'),
    ('Troms', 'Salangen'),
    ('Troms', 'Målselv'),
    ('Troms', 'Sørreisa'),
    ('Troms', 'Dyrøy'),
    ('Troms', 'Tranøy'),
    ('Troms', 'Torsken'),
    ('Troms', 'Berg'),
    ('Troms', 'Lenvik'),
    ('Troms', 'Balsfjord'),
    ('Troms', 'Karlsøy'),
    ('Troms', 'Lyngen'),
    ('Troms', 'Storfjord'),
    ('Troms', 'Kåfjord'),
    ('Troms', 'Skjervøy'),
    ('Troms', 'Nordreisa'),
    ('Troms', 'Kvænangen'),
    ('Finnmark', 'Vardø'),
    ('Finnmark', 'Vadsø'),
    ('Finnmark', 'Hammerfest'),
    ('Finnmark', 'Kautokeino'),
    ('Finnmark', 'Alta'),
    ('Finnmark', 'Loppa'),
    ('Finnmark', 'Hasvik'),
    ('Finnmark', 'Kvalsund'),
    ('Finnmark', 'Måsøy'),
    ('Finnmark', 'Nordkapp'),
    ('Finnmark', 'Porsanger'),
    ('Finnmark', 'Karasjok'),
    ('Finnmark', 'Lebesby'),
    ('Finnmark', 'Gamvik'),
    ('Finnmark', 'Berlevåg'),
    ('Finnmark', 'Tana'),
    ('Finnmark', 'Nesseby'),
    ('Finnmark', 'Båtsfjord'),
    ('Finnmark', 'Sør-Varanger');